/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.test.ui.pages

import org.openqa.selenium.By
import org.scalatest.matchers.should.Matchers

trait CommonElements extends BasePage with Matchers{

  def load(key: String): By =
    elements(key)

  val elements: Map[String, By] = Map(
    //Common Elements
    "yes"                  -> By.id("value"),
    "no"                   -> By.id("value-no"),
    "save and continue"    -> By.cssSelector("#main-content > div > div > form > button"),
    "continue"             -> By.id("continue"),
    "confirm"              -> By.xpath("//*[contains(text(),'Confirm')]"),
    "back"                 -> By.cssSelector("a.govuk-back-link"),
    "remove account"       -> By.cssSelector("#main-content > div > div > div.govuk-form-group > ul > li:nth-child(1) > span.hmrc-add-to-a-list__remove > a"),
    "change"               -> By.cssSelector("#main-content > div > div > div.govuk-form-group > ul > li > span.hmrc-add-to-a-list__change > a"),
    "return to overview"   -> By.id("returnToOverviewPageBtn"),
    "remove"               -> By.id("remove"),
    "Yes for gateway question" -> By.xpath("//dd[contains(text(),'Yes')]"),
    "No for gateway question" -> By.xpath("//dd[contains(text(),'No')]"),
    "amount"                  -> By.id("amount"),

    //Tailoring Elements
    "addSections"                   -> By.id("addSectionsLink"),
    "addDividend"                   -> By.id("dividends"),
    "addInterest"                   -> By.id("interest"),
    "addGiftAid"                    -> By.id("gift-aid"),
    "addEmployment"                 -> By.id("employment"),
    "addCisSection"                 -> By.id("cis"),
    "addPension"                    -> By.id("pensions"),
    "addGains"                      -> By.id("gains"),

    //Dividends Elements
    "dividends"                     -> By.id("dividends_link"),
    "UK dividends amount"           -> By.id("amount"),
    "UK other dividends amount"     -> By.id("amount"),
    "change dividends from the uk summary" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(1) > dd.govuk-summary-list__actions > a"),
    "change uk dividends amount"    -> By.cssSelector("#main-content > div > div > dl > div:nth-child(2) > dd.govuk-summary-list__actions > a"),
    "change other dividends amount" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(3) > dd.govuk-summary-list__actions > a"),
    "change stock dividends" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(4) > dd.govuk-summary-list__actions > a"),
    "change value of stock dividends" -> By.xpath("//*[contains(text(),'Value of stock dividends')]/parent::div/dd[2]"),
    "change value of free or redeemable shares" -> By.xpath("//*[contains(text(),'Free or redeemable shares')]/parent::div/dd[2]"),
    "change value of close company loan written off or released" -> By.xpath("//*[contains(text(),'Close company loan written off or released')]/parent::div/dd[2]"),

    //Interest Elements
    "Interest from savings and securities"  -> By.id("interest_link"),
    "UK Interest"  -> By.id("interest_link"),
    "Interest from gilt-edged or accrued income securities"  -> By.cssSelector("#main-content > div > div > ol > li:nth-child(2) > span.app-task-list__task-name > a"),
    "UK untaxed interest amount earned" -> By.id("untaxedAmount"),
    "UK taxed interest amount earned"   -> By.id("taxedAmount"),
    "UK untaxed interest updated amount earned" -> By.id("amount"),
    "UK taxed interest updated amount earned"   -> By.id("amount"),
    "UK untaxed interest account name"  -> By.id("untaxedAccountName"),
    "UK taxed interest account name"    -> By.id("taxedAccountName"),
    "first account change" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(1) > dd > ul > li:nth-child(1) > a"),
    "second account change" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(2) > dd > ul > li:nth-child(1) > a"),
    "change interest from the uk summary" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(1) > dd.govuk-summary-list__actions > a"),
    "change uk untaxed interest accounts summary" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(2) > dd.govuk-summary-list__actions > a"),
    "change uk taxed interest accounts summary"  -> By.cssSelector("#main-content > div > div > dl > div:nth-child(3) > dd.govuk-summary-list__actions > a"),
    "remove interest" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(1) > dd > ul > li:nth-child(2) > a"),
    "first" -> By.id("value"),
    "second" -> By.id("value-2"),
    "third" -> By.id("value-3"),
    "fourth" -> By.id("value-4"),
    "fifth" -> By.id("value-5"),

    //Employment Elements
    "employment"                       -> By.id("employment_link"),
    "employment details"               -> By.linkText("Employment details"),
    "view employer"                    -> By.cssSelector("#main-content > div > div > dl:nth-of-type(1) > div > dd > a"),
    "benefits"                         -> By.linkText("Benefits"),
    "employment benefits"              -> By.id("employment-benefits_link"),
    "expenses"                         -> By.linkText("Expenses"),
    "view expenses"                    -> By.cssSelector("#main-content > div > div > dl:nth-of-type(2) > div > dd > a"),
    "add expenses"                     -> By.id("add-expenses"),
    "change expenses"                  -> By.cssSelector("#main-content > div > div > dl:nth-child(10) > div > dd > ul > li:nth-child(1) > a"),
    "view first employer"              -> By.cssSelector("#main-content > div > div > dl:nth-of-type(1) > div:nth-child(1) > dd > a"),
    "change employer"                  -> By.cssSelector("#main-content > div > div > dl:nth-child(6) > div > dd > ul > li:nth-child(1) > a"),
    "return to employment summary"     -> By.id("returnToEmploymentSummaryBtn"),
    "return to employer"               -> By.id("returnToEmployerBtn"),
    "Clickable employment"             -> By.id("employment_link"),
    "Employer name"                    -> By.id("name"),
    "PAYE reference"                   -> By.id("payeRef"),
    "Payroll id"                       -> By.id("payrollId"),
    "Day"                              -> By.id("amount-day"),
    "Month"                            -> By.id("amount-month"),
    "Year"                             -> By.id("amount-year"),
    "Start Day"                        -> By.id("startAmount-day"),
    "Start Month"                      -> By.id("startAmount-month"),
    "Start Year"                       -> By.id("startAmount-year"),
    "End Day"                          -> By.id("endAmount-day"),
    "End Month"                        -> By.id("endAmount-month"),
    "End Year"                         -> By.id("endAmount-year"),
    "Pay"                              -> By.id("amount"),
    "Tax"                              -> By.id("amount"),
    "amount"                           -> By.id("amount"),
    "change employment"                -> By.cssSelector("#main-content > div > div > dl > div > dd.govuk-summary-list__actions > ul > li:nth-child(1) > a"),
    "first change employment"          -> By.cssSelector("#main-content > div > div > dl:nth-child(6) > div:nth-child(1) > dd > ul > li:nth-child(1) > a"),
    "second change employment"         -> By.cssSelector("#main-content > div > div > dl:nth-child(6) > div:nth-child(2) > dd > ul > li:nth-child(1) > a"),
    "third change employment"          -> By.cssSelector("#main-content > div > div > dl:nth-child(6) > div:nth-child(3) > dd > ul > li:nth-child(1) > a"),
    "change Employer"                  -> By.cssSelector("#main-content > div > div > dl > div:nth-child(1) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change start date"                -> By.cssSelector("#main-content > div > div > dl > div:nth-child(2) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change still working reference"   -> By.cssSelector("#main-content > div > div > dl > div:nth-child(3) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change end date"                  -> By.cssSelector("#main-content > div > div > dl > div:nth-child(4) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change PAYE reference"            -> By.cssSelector("#main-content > div > div > dl > div:nth-child(5) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change payroll id"                -> By.cssSelector("#main-content > div > div > dl > div:nth-child(6) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change pay received"              -> By.cssSelector("#main-content > div > div > dl > div:nth-child(7) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change tax taken from pay"        -> By.cssSelector("#main-content > div > div > dl > div:nth-child(8) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "Employments list item"            -> By.cssSelector("#employer-h2"),
    "Expenses list item"               -> By.cssSelector("#expense-h2"),
    "remove employment"                -> By.cssSelector("#main-content > div > div > dl:nth-child(6) > div > dd > ul > li:nth-child(2) > a"),
    "third remove employment"          -> By.cssSelector("#main-content > div > div > dl:nth-child(6) > div:nth-child(3) > dd > ul > li:nth-child(2) > a"),
    "remove expenses"                  -> By.cssSelector("#main-content > div > div > dl:nth-child(8) > div > dd > ul > li:nth-child(2) > a"),
    "Remove expenses"                  -> By.cssSelector("#remove-expenses-button-id"),
    "change expenses section"          -> By.cssSelector("#main-content > div > div > div:nth-child(6) > ul > li > span.hmrc-add-to-a-list__change > a"),
    "Add an employer"                  -> By.xpath("//a[contains(text(),'Add an employer')]"),
    "Add another employer"             -> By.linkText("Add another employer"),
    "Remove employer"                  -> By.id("remove-employer-button-id"),
    "student loans"                    -> By.id("student-loans_link"),
    "student loan repayments"          -> By.cssSelector("#studentLoans"),
    "postgraduate loan repayments"     -> By.cssSelector("#studentLoans-2"),
    "no repayments"                    -> By.cssSelector("#studentLoans-4"),
    "change student loan repayments"   -> By.cssSelector("#main-content > div > div > dl > div:nth-child(1) > dd.govuk-summary-list__actions > a > span:nth-child(1)"),
    "student loans amount change" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(2) > dd.govuk-summary-list__actions > a > span:nth-child(1)"),
    "postgraduate loans amount change" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(3) > dd.govuk-summary-list__actions > a > span:nth-child(1)"),
    "cannot update" -> By.cssSelector("#main-content > div > div > div.govuk-inset-text"),
    "PAYE employment change" -> By.cssSelector("#main-content > div > div > dl:nth-child(3) > div > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a > span:nth-child(1)"),
    "Employment remove confirm" -> By.id("remove-employer-button-id"),

    //GiftAid Elements
    "GiftAid" -> By.id("giftAid_link"),
    "Amount donated using Gift Aid" -> By.id("amount"),
    "Amount donated as one-off payments" -> By.id("amount"),
    "Amount donated to overseas charities using Gift Aid" -> By.id("amount"),
    "Name of overseas charity" -> By.id("name"),
    "Amount to add to last tax year" -> By.id("amount"),
    "Amount to add to this tax year" -> By.id("amount"),
    "Total value of qualifying shares or securities" -> By.id("amount"),
    "Value of land or property" -> By.id("amount"),
    "Value of qualifying shares, securities, land or property donated to overseas charities" -> By.id("amount"),
    "Name of overseas charity you donated shares, securities, land or property to" -> By.id("name"),
    "Name of overseas charity your client donated shares, securities, land or property to" -> By.id("name"),
    "change donations to charity summary" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(1) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change amount donated to charity using Gift Aid" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(2) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change amount of one-off donations to charity using Gift Aid" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(3) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change amount donated to overseas charities by using Gift Aid" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(4) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change overseas charities names" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(5) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change amount of donation to add to last tax year" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(6) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change amount of donation added to this tax year" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(7) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change value of shares or securities" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(8) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change value of land or property" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(9) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change value of shares, securities, land or property" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(10) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change overseas charities shares, securities, land or property were donated to" -> By.cssSelector("#main-content > div > div > dl > div:nth-child(11) > dd.govuk-summary-list__actions.govuk-\\!-width-one-third > a"),
    "change charity name" -> By.cssSelector("#main-content > div > div > div.govuk-form-group > ul > li:nth-child(1) > span.hmrc-add-to-a-list__change > a"),

    //Crystallisation Elements
    "I agree - Submit Income Tax Return" -> By.cssSelector("#agree"),
    "Client SA UTR" -> By.id("utr"),
    "View and Change Continue" -> By.id("continue-button"),

    //Construction Industry Scheme Elements
    "cis deductions"              -> By.id("cis_link"),
    "first contractor"            -> By.cssSelector("tbody > tr.govuk-table__row:nth-child(1) > th > a"),
    "second contractor"           -> By.cssSelector("tbody > tr.govuk-table__row:nth-child(2) > th > a"),
    "third contractor"            -> By.cssSelector("tbody > tr.govuk-table__row:nth-child(3) > th > a"),
    "cis return to overview"      -> By.id("return-to-overview-button-id"),
    "first month view"            -> By.cssSelector("#main-content > div > div > dl > div > dd > a"),
    "second month view"           -> By.cssSelector("#main-content > div > div > dl > div:nth-child(2) > dd > a"),
    "return to cis summary"       -> By.id("return-to-summary-button-id"),
    "return to contractor"        -> By.id("return-to-contractor-button-id"),
    "first month change"          -> By.cssSelector("#main-content > div > div > dl > div:nth-child(1) > dd:nth-child(2) > a"),
    "first month remove"          -> By.cssSelector("#main-content > div > div > dl > div:nth-child(1) > dd:nth-child(3) > a"),
    "change end of tax month"     -> By.cssSelector("#main-content > div > div > dl > div:nth-child(2) > dd:nth-child(3) > a"),
    "change labour"               -> By.cssSelector("#main-content > div > div > dl > div:nth-child(3) > dd:nth-child(3) > a"),
    "change cis deduction"        -> By.cssSelector("#main-content > div > div > dl > div:nth-child(4) > dd:nth-child(3) > a"),
    "change paid for materials"   -> By.cssSelector("#main-content > div > div > dl > div:nth-child(5) > dd:nth-child(3) > a"),
    "change cost of materials"    -> By.cssSelector("#main-content > div > div > dl > div:nth-child(6) > dd:nth-child(3) > a"),
    "Add another contractor"      -> By.id("add-contractor"),
    "Contractor name"             -> By.id("contractorName"),
    "Employer Reference Number"   -> By.id("employerReferenceNumber"),
    "Add another CIS deduction"   -> By.id("add-another-link"),
    "Add a CIS deduction"         -> By.id("add-link"),
    "Tax month ending"            -> By.id("month"),
    "Add a contractor"            -> By.id("add-contractor"),
    "CIS save and continue"       -> By.id("save-and-continue-button-id"),
    "Remove period"               -> By.id("remove-period-button-id"),
    "CIS deductions change"  -> By.xpath ("//*[@id=\"main-content\"]/div/div/dl/div/dd[2]/a/span[1]"),//("//dt[contains(text,'')]/../dd[2]/a/span[1]"),
    "CIS You cannot update text"  -> By.cssSelector("#main-content > div > div > div.govuk-inset-text"),
    "Updated for Cis"                -> By.xpath("//*[contains(text(),'Updated')]/../../span/a[@id='cis_link']"),
    "Cannot Update for Cis"                -> By.xpath("//*[contains(text(),'Cannot update')]/../../span/a[@id='cis_link']"),

    //State Benefits Elements
    "State benefits" -> By.id("stateBenefits_link"),
    "Jobseeker’s Allowance" -> By.id("jobSeekersAllowance_link"),
    "Add missing claim" -> By.id("add-missing-claim-button-id"),
    "claim day" -> By.id("value-for-day"),
    "claim month" -> By.id("value-for-month"),
    "claim year" -> By.id("value-for-year"),
    "remove claim" -> By.id("remove-link-id"),
    "Remove claim" -> By.id("remove-claim-button-id"),
    "Restore claim" -> By.id("restore-claim-button-id"),
    "first view" -> By.cssSelector("#benefits-summary-list-id > div:nth-child(1) > dd:nth-child(3) > a:nth-child(1)"),
    "first ignored view" -> By.cssSelector("#ignored-benefits-summary-list-id > div:nth-child(1) > dd:nth-child(3) > a:nth-child(1)"),
    "first view in year" -> By.cssSelector("div.govuk-summary-list__row:nth-child(1) > dd:nth-child(2) > a:nth-child(1)"),
    "state benefit change start date" -> By.cssSelector("div.govuk-summary-list__row:nth-child(1) > dd:nth-child(3) > a:nth-child(1) > span:nth-child(1)"),
    "state benefit change end date question" -> By.cssSelector("div.govuk-summary-list__row:nth-child(2) > dd:nth-child(3) > a:nth-child(1) > span:nth-child(1)"),
    "state benefit change end date" -> By.cssSelector("div.govuk-summary-list__row:nth-child(3) > dd:nth-child(3) > a:nth-child(1) > span:nth-child(1)"),
    "state benefit change tax taken question" -> By.cssSelector("div.govuk-summary-list__row:nth-child(4) > dd:nth-child(3) > a:nth-child(1) > span:nth-child(1)"),
    "state benefit change amount" -> By.cssSelector("div.govuk-summary-list__row:nth-child(5) > dd:nth-child(3) > a:nth-child(1) > span:nth-child(1)"),
    "state benefit save and continue" -> By.id("save-and-continue-button-id"),
    "state benefit back" -> By.id("back-link"),
    "Employment and Support Allowance" -> By.id("employmentSupportAllowance_link"),

    //View Estimation Elements
    "Update tax calculation"   -> By.id("updateTaxCalculation"),
    "Go to Income Tax Account" -> By.id("continue-button"),

    //Pensions Elements
    "pensions"              -> By.id("pensions_link"),
    "Payments into pensions" -> By.id("payments-into-pensions-link"),
    "Unauthorised payments from pensions" ->  By.id("unauthorised-payments-from-pensions-link"),
    "Yes, unauthorised payments that resulted in a surcharge" ->  By.id("unauthorisedPayments"),
    "Yes, unauthorised payments that did not result in a surcharge" ->  By.id("unauthorisedPayments-2"),
    "No" ->  By.id("unauthorisedPayments-4"),
    "amount in pounds"      -> By.id("amount-2"),
    "PSTR"      -> By.id("taxReferenceId"),
    "yes on"                  -> By.id("value-yes"),
    "Add another Pensions Scheme Tax Reference"  -> By.id("add-another-pension-link"),
    "Change PSTR"  -> By.cssSelector("#pensionIncomeSummaryList > dl > div:nth-child(1) > dd.hmrc-add-to-a-list__change > a"),
    "Remove PSTR"  -> By.cssSelector("#pensionIncomeSummaryList > dl > div:nth-child(1) > dd.hmrc-add-to-a-list__remove > a"),
    "Remove Reference" -> By.id("remove-pension-button-id"),
    "Overseas pensions"      -> By.id("overseas-pensions-summary-link"),
    "Income from overseas pensions" -> By.id("income-from-overseas-pensions-link"),
    "Country"               -> By.id("countryId"),
    "Country List"          -> By.id("countryId__listbox"),
    "amount before tax"     -> By.id("amount-1"),
    "tax paid"              -> By.id("amount-2"),
    "amount in pounds"      -> By.id("amount-2"),
    "pensions scheme save and continue"      -> By.id("continue"),
    "add another pension scheme" -> By.id("add-another-pension-link"),

  //Gains Elements
    "Gains from policies and contracts" -> By.id("gains_link"),
    "Life Insurance"                    -> By.cssSelector("[value='lifeInsurance']"),
    "Full or part surrender"            -> By.cssSelector("[value='Full or part surrender']"),
    "Other"                             -> By.id("other-text"),
    "Sale or assignment of a policy"    -> By.id("policy-event-3"),
    "What caused this gain?"            -> By.id("other-text-input"),
    "Policy number"                     -> By.id("value"),
    "Gains Year"                        -> By.id("year"),
    "Policy remove"                     -> By.id("policy-remove"),
    "Updated Tag"                       -> By.xpath("//*[contains(text(),'Updated')]/../../span/a[@id='gains_link']"),
    "Add a policy"                      -> By.id("continue"),
    "Excluded for Gains"                -> By.xpath("//*[contains(text(),'Excluded')]/../../span/a[@id='gains_link']"),
    "Voided ISA"                        -> By.cssSelector("[value='voidedIsa']")
  )
}
